--
-- PostgreSQL database dump
--

\restrict 4CEyuVHZsjchV1dvczrvUZMqMDYpit7TAwKPtW3MJg6Ix3DF4HmG0xx6dj1uPMU

-- Dumped from database version 15.17
-- Dumped by pg_dump version 15.17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO clm_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO clm_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO clm_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO clm_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO clm_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO clm_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_auditlog; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_auditlog (
    id bigint NOT NULL,
    action character varying(50) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    details text NOT NULL,
    ip_address inet,
    old_value text NOT NULL,
    new_value text NOT NULL,
    contract_id bigint,
    user_id integer
);


ALTER TABLE public.contracts_auditlog OWNER TO clm_user;

--
-- Name: contracts_auditlog_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_auditlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_auditlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_comment; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_comment (
    id bigint NOT NULL,
    text text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_internal boolean NOT NULL,
    contract_id bigint NOT NULL,
    user_id integer
);


ALTER TABLE public.contracts_comment OWNER TO clm_user;

--
-- Name: contracts_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_contract; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_contract (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    contract_type character varying(20) NOT NULL,
    description text NOT NULL,
    party_a character varying(255) NOT NULL,
    party_b character varying(255) NOT NULL,
    contract_value numeric(18,0),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    start_date date,
    end_date date,
    renewal_reminder_days integer NOT NULL,
    auto_renew boolean NOT NULL,
    renewal_period_months integer NOT NULL,
    status character varying(20) NOT NULL,
    document character varying(100),
    notes text NOT NULL,
    created_by_id integer,
    owner_id integer,
    parent_contract_id bigint,
    is_draft_generated boolean NOT NULL,
    draft_generated_at timestamp with time zone
);


ALTER TABLE public.contracts_contract OWNER TO clm_user;

--
-- Name: contracts_contract_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_contract ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contract_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_contractdata; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_contractdata (
    id bigint NOT NULL,
    data jsonb NOT NULL,
    submitted_at timestamp with time zone NOT NULL,
    contract_id bigint NOT NULL,
    submitted_by_id integer,
    version integer NOT NULL,
    CONSTRAINT contracts_contractdata_version_check CHECK ((version >= 0))
);


ALTER TABLE public.contracts_contractdata OWNER TO clm_user;

--
-- Name: contracts_contractdata_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_contractdata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contractdata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_contractdatafile; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_contractdatafile (
    id bigint NOT NULL,
    field_key character varying(100) NOT NULL,
    file character varying(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    contract_data_id bigint NOT NULL
);


ALTER TABLE public.contracts_contractdatafile OWNER TO clm_user;

--
-- Name: contracts_contractdatafile_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_contractdatafile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contractdatafile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_contractdocument; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_contractdocument (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    document character varying(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    description text NOT NULL,
    contract_id bigint NOT NULL,
    uploaded_by_id integer,
    version integer NOT NULL,
    is_current boolean NOT NULL,
    CONSTRAINT contracts_contractdocument_version_check CHECK ((version >= 0))
);


ALTER TABLE public.contracts_contractdocument OWNER TO clm_user;

--
-- Name: contracts_contractdocument_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_contractdocument ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contractdocument_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_contractdraft; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_contractdraft (
    id bigint NOT NULL,
    version integer NOT NULL,
    file character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    contract_id bigint NOT NULL,
    template_id bigint,
    CONSTRAINT contracts_contractdraft_version_check CHECK ((version >= 0))
);


ALTER TABLE public.contracts_contractdraft OWNER TO clm_user;

--
-- Name: contracts_contractdraft_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_contractdraft ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contractdraft_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_contractfield; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_contractfield (
    id bigint NOT NULL,
    field_key character varying(100) NOT NULL,
    label character varying(255) NOT NULL,
    field_type character varying(20) NOT NULL,
    required boolean NOT NULL,
    options jsonb,
    "position" integer NOT NULL,
    contract_type_id bigint NOT NULL,
    CONSTRAINT contracts_contractfield_position_check CHECK (("position" >= 0))
);


ALTER TABLE public.contracts_contractfield OWNER TO clm_user;

--
-- Name: contracts_contractfield_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_contractfield ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contractfield_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_contractparticipant; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_contractparticipant (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    added_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    contract_id bigint NOT NULL,
    user_id integer,
    external_email character varying(254),
    external_name character varying(255) NOT NULL,
    notification_preference character varying(20) NOT NULL
);


ALTER TABLE public.contracts_contractparticipant OWNER TO clm_user;

--
-- Name: contracts_contractparticipant_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_contractparticipant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contractparticipant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_contractquarter; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_contractquarter (
    id bigint NOT NULL,
    quarter_number smallint NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    target_amount numeric(14,2) NOT NULL,
    contract_id bigint NOT NULL,
    CONSTRAINT contracts_contractquarter_quarter_number_check CHECK ((quarter_number >= 0))
);


ALTER TABLE public.contracts_contractquarter OWNER TO clm_user;

--
-- Name: contracts_contractquarter_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_contractquarter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contractquarter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_contractrolepermission; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_contractrolepermission (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    permission character varying(32) NOT NULL,
    allowed boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.contracts_contractrolepermission OWNER TO clm_user;

--
-- Name: contracts_contractrolepermission_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_contractrolepermission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contractrolepermission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_contractsignature; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_contractsignature (
    id bigint NOT NULL,
    signature_data text NOT NULL,
    signed_at timestamp with time zone NOT NULL,
    ip_address inet,
    user_agent character varying(255) NOT NULL,
    contract_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.contracts_contractsignature OWNER TO clm_user;

--
-- Name: contracts_contractsignature_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_contractsignature ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contractsignature_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_contracttarget; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_contracttarget (
    id bigint NOT NULL,
    annual_target numeric(14,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    contract_id bigint NOT NULL
);


ALTER TABLE public.contracts_contracttarget OWNER TO clm_user;

--
-- Name: contracts_contracttarget_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_contracttarget ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contracttarget_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_contracttemplate; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_contracttemplate (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    content text NOT NULL,
    active boolean NOT NULL,
    version integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    contract_type_id bigint NOT NULL,
    CONSTRAINT contracts_contracttemplate_version_check CHECK ((version >= 0))
);


ALTER TABLE public.contracts_contracttemplate OWNER TO clm_user;

--
-- Name: contracts_contracttemplate_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_contracttemplate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contracttemplate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_contracttypedefinition; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_contracttypedefinition (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    active boolean NOT NULL,
    is_template_based boolean NOT NULL
);


ALTER TABLE public.contracts_contracttypedefinition OWNER TO clm_user;

--
-- Name: contracts_contracttypedefinition_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_contracttypedefinition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_contracttypedefinition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_finalapproveddocument; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_finalapproveddocument (
    id bigint NOT NULL,
    document character varying(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    notes text NOT NULL,
    contract_id bigint NOT NULL,
    uploaded_by_id integer
);


ALTER TABLE public.contracts_finalapproveddocument OWNER TO clm_user;

--
-- Name: contracts_finalapproveddocument_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_finalapproveddocument ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_finalapproveddocument_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_reminderconfiguration; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_reminderconfiguration (
    id bigint NOT NULL,
    reminder_type character varying(20) NOT NULL,
    scope character varying(20) NOT NULL,
    enabled boolean NOT NULL,
    days_before_trigger integer NOT NULL,
    frequency character varying(20) NOT NULL,
    max_occurrences integer NOT NULL,
    recipient_roles character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    description text NOT NULL,
    contract_id bigint,
    contract_type_id bigint
);


ALTER TABLE public.contracts_reminderconfiguration OWNER TO clm_user;

--
-- Name: contracts_reminderconfiguration_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_reminderconfiguration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_reminderconfiguration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contracts_reminderlog; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.contracts_reminderlog (
    id bigint NOT NULL,
    reminder_type character varying(20) NOT NULL,
    scheduled_date timestamp with time zone NOT NULL,
    sent_date timestamp with time zone,
    recipients text NOT NULL,
    status character varying(20) NOT NULL,
    error_message text NOT NULL,
    email_subject character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    contract_id bigint NOT NULL,
    reminder_config_id bigint NOT NULL
);


ALTER TABLE public.contracts_reminderlog OWNER TO clm_user;

--
-- Name: contracts_reminderlog_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.contracts_reminderlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_reminderlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO clm_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL,
    clocked_time timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO clm_user;

--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL,
    minute character varying(240) NOT NULL,
    hour character varying(96) NOT NULL,
    day_of_week character varying(64) NOT NULL,
    day_of_month character varying(124) NOT NULL,
    month_of_year character varying(64) NOT NULL,
    timezone character varying(63) NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO clm_user;

--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL,
    every integer NOT NULL,
    period character varying(24) NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO clm_user;

--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO clm_user;

--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO clm_user;

--
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO clm_user;

--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO clm_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO clm_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: clm_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: clm_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO clm_user;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.auth_group (id, name) FROM stdin;
1	Legal Team
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add crontab	7	add_crontabschedule
26	Can change crontab	7	change_crontabschedule
27	Can delete crontab	7	delete_crontabschedule
28	Can view crontab	7	view_crontabschedule
29	Can add interval	8	add_intervalschedule
30	Can change interval	8	change_intervalschedule
31	Can delete interval	8	delete_intervalschedule
32	Can view interval	8	view_intervalschedule
33	Can add periodic task	9	add_periodictask
34	Can change periodic task	9	change_periodictask
35	Can delete periodic task	9	delete_periodictask
36	Can view periodic task	9	view_periodictask
37	Can add periodic tasks	10	add_periodictasks
38	Can change periodic tasks	10	change_periodictasks
39	Can delete periodic tasks	10	delete_periodictasks
40	Can view periodic tasks	10	view_periodictasks
41	Can add solar event	11	add_solarschedule
42	Can change solar event	11	change_solarschedule
43	Can delete solar event	11	delete_solarschedule
44	Can view solar event	11	view_solarschedule
45	Can add clocked	12	add_clockedschedule
46	Can change clocked	12	change_clockedschedule
47	Can delete clocked	12	delete_clockedschedule
48	Can view clocked	12	view_clockedschedule
49	Can add contract	13	add_contract
50	Can change contract	13	change_contract
51	Can delete contract	13	delete_contract
52	Can view contract	13	view_contract
53	Can add contract signature	14	add_contractsignature
54	Can change contract signature	14	change_contractsignature
55	Can delete contract signature	14	delete_contractsignature
56	Can view contract signature	14	view_contractsignature
57	Can add contract document	15	add_contractdocument
58	Can change contract document	15	change_contractdocument
59	Can delete contract document	15	delete_contractdocument
60	Can view contract document	15	view_contractdocument
61	Can add comment	16	add_comment
62	Can change comment	16	change_comment
63	Can delete comment	16	delete_comment
64	Can view comment	16	view_comment
65	Can add audit log	17	add_auditlog
66	Can change audit log	17	change_auditlog
67	Can delete audit log	17	delete_auditlog
68	Can view audit log	17	view_auditlog
69	Can add contract participant	18	add_contractparticipant
70	Can change contract participant	18	change_contractparticipant
71	Can delete contract participant	18	delete_contractparticipant
72	Can view contract participant	18	view_contractparticipant
73	Can add contract type definition	19	add_contracttypedefinition
74	Can change contract type definition	19	change_contracttypedefinition
75	Can delete contract type definition	19	delete_contracttypedefinition
76	Can view contract type definition	19	view_contracttypedefinition
77	Can add contract template	20	add_contracttemplate
78	Can change contract template	20	change_contracttemplate
79	Can delete contract template	20	delete_contracttemplate
80	Can view contract template	20	view_contracttemplate
81	Can add contract field	21	add_contractfield
82	Can change contract field	21	change_contractfield
83	Can delete contract field	21	delete_contractfield
84	Can view contract field	21	view_contractfield
85	Can add contract draft	22	add_contractdraft
86	Can change contract draft	22	change_contractdraft
87	Can delete contract draft	22	delete_contractdraft
88	Can view contract draft	22	view_contractdraft
89	Can add contract data	23	add_contractdata
90	Can change contract data	23	change_contractdata
91	Can delete contract data	23	delete_contractdata
92	Can view contract data	23	view_contractdata
93	Can add contract data file	24	add_contractdatafile
94	Can change contract data file	24	change_contractdatafile
95	Can delete contract data file	24	delete_contractdatafile
96	Can view contract data file	24	view_contractdatafile
97	Can add reminder configuration	25	add_reminderconfiguration
98	Can change reminder configuration	25	change_reminderconfiguration
99	Can delete reminder configuration	25	delete_reminderconfiguration
100	Can view reminder configuration	25	view_reminderconfiguration
101	Can add reminder log	26	add_reminderlog
102	Can change reminder log	26	change_reminderlog
103	Can delete reminder log	26	delete_reminderlog
104	Can view reminder log	26	view_reminderlog
105	Can add contract target	27	add_contracttarget
106	Can change contract target	27	change_contracttarget
107	Can delete contract target	27	delete_contracttarget
108	Can view contract target	27	view_contracttarget
109	Can add contract quarter	28	add_contractquarter
110	Can change contract quarter	28	change_contractquarter
111	Can delete contract quarter	28	delete_contractquarter
112	Can view contract quarter	28	view_contractquarter
113	Can add contract role permission	29	add_contractrolepermission
114	Can change contract role permission	29	change_contractrolepermission
115	Can delete contract role permission	29	delete_contractrolepermission
116	Can view contract role permission	29	view_contractrolepermission
117	Can add final approved document	30	add_finalapproveddocument
118	Can change final approved document	30	change_finalapproveddocument
119	Can delete final approved document	30	delete_finalapproveddocument
120	Can view final approved document	30	view_finalapproveddocument
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$600000$lAnGQMu8Txae2VZES61DSb$EI8cX//6nDrBfFKoY8ZDpx/V/zDbGcvfDlmgOngRIyw=	2026-04-01 02:05:18.837308+00	t	admin			admin@local	t	t	2026-04-01 02:04:46.843584+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: contracts_auditlog; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_auditlog (id, action, "timestamp", details, ip_address, old_value, new_value, contract_id, user_id) FROM stdin;
\.


--
-- Data for Name: contracts_comment; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_comment (id, text, created_at, updated_at, is_internal, contract_id, user_id) FROM stdin;
\.


--
-- Data for Name: contracts_contract; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_contract (id, title, contract_type, description, party_a, party_b, contract_value, created_at, updated_at, start_date, end_date, renewal_reminder_days, auto_renew, renewal_period_months, status, document, notes, created_by_id, owner_id, parent_contract_id, is_draft_generated, draft_generated_at) FROM stdin;
\.


--
-- Data for Name: contracts_contractdata; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_contractdata (id, data, submitted_at, contract_id, submitted_by_id, version) FROM stdin;
\.


--
-- Data for Name: contracts_contractdatafile; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_contractdatafile (id, field_key, file, uploaded_at, contract_data_id) FROM stdin;
\.


--
-- Data for Name: contracts_contractdocument; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_contractdocument (id, title, document, uploaded_at, description, contract_id, uploaded_by_id, version, is_current) FROM stdin;
\.


--
-- Data for Name: contracts_contractdraft; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_contractdraft (id, version, file, created_at, contract_id, template_id) FROM stdin;
\.


--
-- Data for Name: contracts_contractfield; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_contractfield (id, field_key, label, field_type, required, options, "position", contract_type_id) FROM stdin;
\.


--
-- Data for Name: contracts_contractparticipant; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_contractparticipant (id, role, added_at, is_active, contract_id, user_id, external_email, external_name, notification_preference) FROM stdin;
\.


--
-- Data for Name: contracts_contractquarter; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_contractquarter (id, quarter_number, start_date, end_date, target_amount, contract_id) FROM stdin;
\.


--
-- Data for Name: contracts_contractrolepermission; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_contractrolepermission (id, role, permission, allowed, updated_at) FROM stdin;
1	OWNER	view_contract	t	2026-03-31 04:52:05.24065+00
2	SALES	view_contract	t	2026-03-31 04:52:05.241387+00
3	LEGAL	view_contract	t	2026-03-31 04:52:05.242057+00
4	CUSTOMER	view_contract	t	2026-03-31 04:52:05.242694+00
5	SIGNATORY	view_contract	t	2026-03-31 04:52:05.243322+00
6	APPROVER	view_contract	t	2026-03-31 04:52:05.243938+00
7	OWNER	edit_contract	t	2026-03-31 04:52:05.244543+00
8	SALES	edit_contract	t	2026-03-31 04:52:05.245152+00
9	LEGAL	edit_contract	f	2026-03-31 04:52:05.24577+00
10	CUSTOMER	edit_contract	f	2026-03-31 04:52:05.246386+00
11	SIGNATORY	edit_contract	f	2026-03-31 04:52:05.246982+00
12	APPROVER	edit_contract	f	2026-03-31 04:52:05.247588+00
13	OWNER	delete_contract	t	2026-03-31 04:52:05.24819+00
14	SALES	delete_contract	f	2026-03-31 04:52:05.248806+00
15	LEGAL	delete_contract	f	2026-03-31 04:52:05.249415+00
16	CUSTOMER	delete_contract	f	2026-03-31 04:52:05.250008+00
17	SIGNATORY	delete_contract	f	2026-03-31 04:52:05.250618+00
18	APPROVER	delete_contract	f	2026-03-31 04:52:05.25122+00
19	OWNER	update_status	t	2026-03-31 04:52:05.251829+00
20	SALES	update_status	f	2026-03-31 04:52:05.25244+00
21	LEGAL	update_status	t	2026-03-31 04:52:05.253039+00
22	CUSTOMER	update_status	f	2026-03-31 04:52:05.253651+00
23	SIGNATORY	update_status	f	2026-03-31 04:52:05.254268+00
24	APPROVER	update_status	t	2026-03-31 04:52:05.25487+00
25	OWNER	manage_participants	t	2026-03-31 04:52:05.255507+00
26	SALES	manage_participants	f	2026-03-31 04:52:05.256107+00
27	LEGAL	manage_participants	t	2026-03-31 04:52:05.256721+00
28	CUSTOMER	manage_participants	f	2026-03-31 04:52:05.257317+00
29	SIGNATORY	manage_participants	f	2026-03-31 04:52:05.257897+00
30	APPROVER	manage_participants	f	2026-03-31 04:52:05.258506+00
31	OWNER	add_document	t	2026-03-31 04:52:05.259103+00
32	SALES	add_document	t	2026-03-31 04:52:05.259715+00
33	LEGAL	add_document	t	2026-03-31 04:52:05.260328+00
34	CUSTOMER	add_document	f	2026-03-31 04:52:05.260922+00
35	SIGNATORY	add_document	f	2026-03-31 04:52:05.261578+00
36	APPROVER	add_document	f	2026-03-31 04:52:05.262184+00
37	OWNER	add_comment	t	2026-03-31 04:52:05.262811+00
38	SALES	add_comment	t	2026-03-31 04:52:05.263444+00
39	LEGAL	add_comment	t	2026-03-31 04:52:05.264035+00
40	CUSTOMER	add_comment	t	2026-03-31 04:52:05.26465+00
41	SIGNATORY	add_comment	f	2026-03-31 04:52:05.265247+00
42	APPROVER	add_comment	t	2026-03-31 04:52:05.26585+00
43	OWNER	edit_structured_data	t	2026-03-31 04:52:05.26647+00
44	SALES	edit_structured_data	t	2026-03-31 04:52:05.267065+00
45	LEGAL	edit_structured_data	t	2026-03-31 04:52:05.267685+00
46	CUSTOMER	edit_structured_data	f	2026-03-31 04:52:05.268284+00
47	SIGNATORY	edit_structured_data	f	2026-03-31 04:52:05.268901+00
48	APPROVER	edit_structured_data	f	2026-03-31 04:52:05.269518+00
49	OWNER	regenerate_draft	f	2026-03-31 04:52:05.270118+00
50	SALES	regenerate_draft	f	2026-03-31 04:52:05.270734+00
51	LEGAL	regenerate_draft	t	2026-03-31 04:52:05.271352+00
52	CUSTOMER	regenerate_draft	f	2026-03-31 04:52:05.271959+00
53	SIGNATORY	regenerate_draft	f	2026-03-31 04:52:05.272571+00
54	APPROVER	regenerate_draft	f	2026-03-31 04:52:05.273183+00
\.


--
-- Data for Name: contracts_contractsignature; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_contractsignature (id, signature_data, signed_at, ip_address, user_agent, contract_id, user_id) FROM stdin;
\.


--
-- Data for Name: contracts_contracttarget; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_contracttarget (id, annual_target, created_at, updated_at, contract_id) FROM stdin;
\.


--
-- Data for Name: contracts_contracttemplate; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_contracttemplate (id, name, content, active, version, created_at, contract_type_id) FROM stdin;
\.


--
-- Data for Name: contracts_contracttypedefinition; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_contracttypedefinition (id, code, name, description, active, is_template_based) FROM stdin;
1	NDA	Non-Disclosure Agreement	Non-Disclosure Agreement	t	f
2	VENDOR	Vendor Agreement	Vendor Agreement	t	f
3	SERVICE	Service Agreement	Service Agreement	t	f
4	EMPLOYMENT	Employment Contract	Employment Contract	t	f
5	LEASE	Lease Agreement	Lease Agreement	t	f
6	PURCHASE	Purchase Agreement	Purchase Agreement	t	f
7	OTHER	Other	Other	t	f
8	GENERAL_TRADE	General Trade Agreement	General Trade Agreement (template-based sales agreement)	t	t
9	MODERN_TRADE	Modern Trade Agreement	Modern Trade Agreement (template-based sales agreement)	t	t
10	DISTRIBUTOR	Distributor Agreement	Distributor Agreement (template-based sales agreement)	t	t
\.


--
-- Data for Name: contracts_finalapproveddocument; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_finalapproveddocument (id, document, uploaded_at, notes, contract_id, uploaded_by_id) FROM stdin;
\.


--
-- Data for Name: contracts_reminderconfiguration; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_reminderconfiguration (id, reminder_type, scope, enabled, days_before_trigger, frequency, max_occurrences, recipient_roles, created_at, updated_at, description, contract_id, contract_type_id) FROM stdin;
1	EXPIRY	GLOBAL	t	30	ONCE	1		2026-03-31 04:52:05.061447+00	2026-03-31 04:52:05.061452+00	Global reminder: Send email 30 days before contract expiry	\N	\N
2	SIGNATURE_PENDING	GLOBAL	t	3	DAILY	0	SIGNATORY,OWNER	2026-03-31 04:52:05.061832+00	2026-03-31 04:52:05.061835+00	Global reminder: Send email 3 days after signature requested (daily)	\N	\N
3	RENEWAL	GLOBAL	t	60	ONCE	1		2026-03-31 04:52:05.062015+00	2026-03-31 04:52:05.062018+00	Global reminder: Send email 60 days before contract renewal is needed	\N	\N
\.


--
-- Data for Name: contracts_reminderlog; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.contracts_reminderlog (id, reminder_type, scheduled_date, sent_date, recipients, status, error_message, email_subject, created_at, updated_at, contract_id, reminder_config_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_clockedschedule; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.django_celery_beat_clockedschedule (id, clocked_time) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_crontabschedule; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.django_celery_beat_crontabschedule (id, minute, hour, day_of_week, day_of_month, month_of_year, timezone) FROM stdin;
1	0	4	*	*	*	UTC
2	0	8	*	*	*	UTC
3	0	9	*	*	*	UTC
4	0	*	*	*	*	UTC
\.


--
-- Data for Name: django_celery_beat_intervalschedule; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.django_celery_beat_intervalschedule (id, every, period) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictask; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.django_celery_beat_periodictask (id, name, task, args, kwargs, queue, exchange, routing_key, expires, enabled, last_run_at, total_run_count, date_changed, description, crontab_id, interval_id, solar_id, one_off, start_time, priority, headers, clocked_id, expire_seconds) FROM stdin;
4	send-reminders-hourly	contracts.tasks.send_reminders	[]	{}	\N	\N	\N	\N	t	2026-04-06 03:00:00.000194+00	143	2026-04-06 03:01:50.133927+00		4	\N	\N	f	\N	\N	{}	\N	\N
1	celery.backend_cleanup	celery.backend_cleanup	[]	{}	\N	\N	\N	\N	t	2026-04-05 04:00:00.008341+00	5	2026-04-05 04:02:55.218324+00		1	\N	\N	f	\N	\N	{}	\N	43200
2	update-expiring-contracts-daily	contracts.tasks.update_expiring_contracts	[]	{}	\N	\N	\N	\N	t	2026-04-05 08:00:00.00854+00	6	2026-04-05 08:00:15.033375+00		2	\N	\N	f	\N	\N	{}	\N	\N
3	schedule-reminders-daily	contracts.tasks.schedule_reminders	[]	{}	\N	\N	\N	\N	t	2026-04-05 09:00:00.00038+00	6	2026-04-05 09:00:20.037549+00		3	\N	\N	f	\N	\N	{}	\N	\N
\.


--
-- Data for Name: django_celery_beat_periodictasks; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.django_celery_beat_periodictasks (ident, last_update) FROM stdin;
1	2026-03-31 04:52:51.162098+00
\.


--
-- Data for Name: django_celery_beat_solarschedule; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.django_celery_beat_solarschedule (id, event, latitude, longitude) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	django_celery_beat	crontabschedule
8	django_celery_beat	intervalschedule
9	django_celery_beat	periodictask
10	django_celery_beat	periodictasks
11	django_celery_beat	solarschedule
12	django_celery_beat	clockedschedule
13	contracts	contract
14	contracts	contractsignature
15	contracts	contractdocument
16	contracts	comment
17	contracts	auditlog
18	contracts	contractparticipant
19	contracts	contracttypedefinition
20	contracts	contracttemplate
21	contracts	contractfield
22	contracts	contractdraft
23	contracts	contractdata
24	contracts	contractdatafile
25	contracts	reminderconfiguration
26	contracts	reminderlog
27	contracts	contracttarget
28	contracts	contractquarter
29	contracts	contractrolepermission
30	contracts	finalapproveddocument
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-03-31 04:52:04.653094+00
2	auth	0001_initial	2026-03-31 04:52:04.685057+00
3	admin	0001_initial	2026-03-31 04:52:04.694621+00
4	admin	0002_logentry_remove_auto_add	2026-03-31 04:52:04.697649+00
5	admin	0003_logentry_add_action_flag_choices	2026-03-31 04:52:04.7011+00
6	contenttypes	0002_remove_content_type_name	2026-03-31 04:52:04.706834+00
7	auth	0002_alter_permission_name_max_length	2026-03-31 04:52:04.710063+00
8	auth	0003_alter_user_email_max_length	2026-03-31 04:52:04.713216+00
9	auth	0004_alter_user_username_opts	2026-03-31 04:52:04.716213+00
10	auth	0005_alter_user_last_login_null	2026-03-31 04:52:04.719438+00
11	auth	0006_require_contenttypes_0002	2026-03-31 04:52:04.720557+00
12	auth	0007_alter_validators_add_error_messages	2026-03-31 04:52:04.723489+00
13	auth	0008_alter_user_username_max_length	2026-03-31 04:52:04.728752+00
14	auth	0009_alter_user_last_name_max_length	2026-03-31 04:52:04.732469+00
15	auth	0010_alter_group_name_max_length	2026-03-31 04:52:04.736548+00
16	auth	0011_update_proxy_permissions	2026-03-31 04:52:04.73932+00
17	auth	0012_alter_user_first_name_max_length	2026-03-31 04:52:04.742397+00
18	contracts	0001_initial	2026-03-31 04:52:04.814908+00
19	contracts	0002_dynamic_contract_data	2026-03-31 04:52:04.877792+00
20	contracts	0003_remove_contractdraft_contracts_draft_unique_version_and_more	2026-03-31 04:52:04.906491+00
21	contracts	0004_alter_contractdata_options_contractdata_submitted_by_and_more	2026-03-31 04:52:04.957152+00
22	contracts	0005_alter_contractparticipant_unique_together_and_more	2026-03-31 04:52:04.98741+00
23	contracts	0006_reminderconfiguration_reminderlog	2026-03-31 04:52:05.053455+00
24	contracts	0007_populate_default_reminders	2026-03-31 04:52:05.063115+00
25	contracts	0008_sales_agreement_targets	2026-03-31 04:52:05.103668+00
26	contracts	0009_seed_sales_agreement_types	2026-03-31 04:52:05.113248+00
27	contracts	0010_contractdocument_versioning	2026-03-31 04:52:05.126817+00
28	contracts	0011_remove_reminderconfiguration_unique_global_reminder_and_more	2026-03-31 04:52:05.205721+00
29	contracts	0012_change_contract_value_to_idr	2026-03-31 04:52:05.223358+00
30	contracts	0013_increase_contract_value_max	2026-03-31 04:52:05.230689+00
31	contracts	0014_contractrolepermission	2026-03-31 04:52:05.2777+00
32	contracts	0015_rename_contracts_c_role_pe_6f5f66_idx_contracts_c_role_61c809_idx	2026-03-31 04:52:05.279766+00
33	contracts	0016_create_legal_team_group	2026-03-31 04:52:05.287958+00
34	contracts	0017_simplify_contract_statuses	2026-03-31 04:52:05.29696+00
35	contracts	0018_alter_contract_status	2026-03-31 04:52:05.303476+00
36	contracts	0019_alter_contract_status	2026-03-31 04:52:05.30998+00
37	contracts	0020_alter_auditlog_action_and_more	2026-03-31 04:52:05.329361+00
38	django_celery_beat	0001_initial	2026-03-31 04:52:05.345504+00
39	django_celery_beat	0002_auto_20161118_0346	2026-03-31 04:52:05.352419+00
40	django_celery_beat	0003_auto_20161209_0049	2026-03-31 04:52:05.356929+00
41	django_celery_beat	0004_auto_20170221_0000	2026-03-31 04:52:05.359335+00
42	django_celery_beat	0005_add_solarschedule_events_choices	2026-03-31 04:52:05.361709+00
43	django_celery_beat	0006_auto_20180322_0932	2026-03-31 04:52:05.374298+00
44	django_celery_beat	0007_auto_20180521_0826	2026-03-31 04:52:05.380904+00
45	django_celery_beat	0008_auto_20180914_1922	2026-03-31 04:52:05.391644+00
46	django_celery_beat	0006_auto_20180210_1226	2026-03-31 04:52:05.399111+00
47	django_celery_beat	0006_periodictask_priority	2026-03-31 04:52:05.40318+00
48	django_celery_beat	0009_periodictask_headers	2026-03-31 04:52:05.407655+00
49	django_celery_beat	0010_auto_20190429_0326	2026-03-31 04:52:05.468136+00
50	django_celery_beat	0011_auto_20190508_0153	2026-03-31 04:52:05.477201+00
51	django_celery_beat	0012_periodictask_expire_seconds	2026-03-31 04:52:05.481485+00
52	django_celery_beat	0013_auto_20200609_0727	2026-03-31 04:52:05.485787+00
53	django_celery_beat	0014_remove_clockedschedule_enabled	2026-03-31 04:52:05.488484+00
54	django_celery_beat	0015_edit_solarschedule_events_choices	2026-03-31 04:52:05.490933+00
55	django_celery_beat	0016_alter_crontabschedule_timezone	2026-03-31 04:52:05.495324+00
56	django_celery_beat	0017_alter_crontabschedule_month_of_year	2026-03-31 04:52:05.498737+00
57	django_celery_beat	0018_improve_crontab_helptext	2026-03-31 04:52:05.502133+00
58	sessions	0001_initial	2026-03-31 04:52:05.508497+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: clm_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
iin81zaymn5kqpcm4ss2s6ir4mtjs67e	.eJxVjDsOwjAQBe_iGllZ_01Jzxms9a6DA8iR4qRC3B0ipYD2zcx7iYTbWtPWy5ImFmcB4vS7ZaRHaTvgO7bbLGlu6zJluSvyoF1eZy7Py-H-HVTs9VtHhWi0jdbTyKAyQ9CEmghGIKXD4GI2ABmDp8EFVJYduqDZR87GafH-AN5cN5c:1w7kxK:JQ30AZDxnbEP5Z6iuop8TYNSb9xwd-3fUKX-PnRmih4	2026-04-15 02:05:18.846241+00
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 120, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: contracts_auditlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_auditlog_id_seq', 1, false);


--
-- Name: contracts_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_comment_id_seq', 1, false);


--
-- Name: contracts_contract_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_contract_id_seq', 1, false);


--
-- Name: contracts_contractdata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_contractdata_id_seq', 1, false);


--
-- Name: contracts_contractdatafile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_contractdatafile_id_seq', 1, false);


--
-- Name: contracts_contractdocument_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_contractdocument_id_seq', 1, false);


--
-- Name: contracts_contractdraft_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_contractdraft_id_seq', 1, false);


--
-- Name: contracts_contractfield_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_contractfield_id_seq', 1, false);


--
-- Name: contracts_contractparticipant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_contractparticipant_id_seq', 1, false);


--
-- Name: contracts_contractquarter_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_contractquarter_id_seq', 1, false);


--
-- Name: contracts_contractrolepermission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_contractrolepermission_id_seq', 54, true);


--
-- Name: contracts_contractsignature_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_contractsignature_id_seq', 1, false);


--
-- Name: contracts_contracttarget_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_contracttarget_id_seq', 1, false);


--
-- Name: contracts_contracttemplate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_contracttemplate_id_seq', 1, false);


--
-- Name: contracts_contracttypedefinition_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_contracttypedefinition_id_seq', 10, true);


--
-- Name: contracts_finalapproveddocument_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_finalapproveddocument_id_seq', 1, false);


--
-- Name: contracts_reminderconfiguration_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_reminderconfiguration_id_seq', 3, true);


--
-- Name: contracts_reminderlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.contracts_reminderlog_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.django_celery_beat_clockedschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.django_celery_beat_crontabschedule_id_seq', 4, true);


--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.django_celery_beat_intervalschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.django_celery_beat_periodictask_id_seq', 4, true);


--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.django_celery_beat_solarschedule_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 30, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clm_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 58, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: contracts_auditlog contracts_auditlog_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_auditlog
    ADD CONSTRAINT contracts_auditlog_pkey PRIMARY KEY (id);


--
-- Name: contracts_comment contracts_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_comment
    ADD CONSTRAINT contracts_comment_pkey PRIMARY KEY (id);


--
-- Name: contracts_contract contracts_contract_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contract
    ADD CONSTRAINT contracts_contract_pkey PRIMARY KEY (id);


--
-- Name: contracts_contractdata contracts_contractdata_contract_id_version_875822d5_uniq; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractdata
    ADD CONSTRAINT contracts_contractdata_contract_id_version_875822d5_uniq UNIQUE (contract_id, version);


--
-- Name: contracts_contractdata contracts_contractdata_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractdata
    ADD CONSTRAINT contracts_contractdata_pkey PRIMARY KEY (id);


--
-- Name: contracts_contractdatafile contracts_contractdatafile_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractdatafile
    ADD CONSTRAINT contracts_contractdatafile_pkey PRIMARY KEY (id);


--
-- Name: contracts_contractdocument contracts_contractdocument_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractdocument
    ADD CONSTRAINT contracts_contractdocument_pkey PRIMARY KEY (id);


--
-- Name: contracts_contractdraft contracts_contractdraft_contract_id_version_cfa95a1b_uniq; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractdraft
    ADD CONSTRAINT contracts_contractdraft_contract_id_version_cfa95a1b_uniq UNIQUE (contract_id, version);


--
-- Name: contracts_contractdraft contracts_contractdraft_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractdraft
    ADD CONSTRAINT contracts_contractdraft_pkey PRIMARY KEY (id);


--
-- Name: contracts_contractfield contracts_contractfield_contract_type_id_field_k_f7d92014_uniq; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractfield
    ADD CONSTRAINT contracts_contractfield_contract_type_id_field_k_f7d92014_uniq UNIQUE (contract_type_id, field_key);


--
-- Name: contracts_contractfield contracts_contractfield_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractfield
    ADD CONSTRAINT contracts_contractfield_pkey PRIMARY KEY (id);


--
-- Name: contracts_contractparticipant contracts_contractparticipant_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractparticipant
    ADD CONSTRAINT contracts_contractparticipant_pkey PRIMARY KEY (id);


--
-- Name: contracts_contractquarter contracts_contractquarte_contract_id_quarter_numb_381abd62_uniq; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractquarter
    ADD CONSTRAINT contracts_contractquarte_contract_id_quarter_numb_381abd62_uniq UNIQUE (contract_id, quarter_number);


--
-- Name: contracts_contractquarter contracts_contractquarter_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractquarter
    ADD CONSTRAINT contracts_contractquarter_pkey PRIMARY KEY (id);


--
-- Name: contracts_contractrolepermission contracts_contractrolepermission_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractrolepermission
    ADD CONSTRAINT contracts_contractrolepermission_pkey PRIMARY KEY (id);


--
-- Name: contracts_contractrolepermission contracts_contractrolepermission_role_permission_5abf69ee_uniq; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractrolepermission
    ADD CONSTRAINT contracts_contractrolepermission_role_permission_5abf69ee_uniq UNIQUE (role, permission);


--
-- Name: contracts_contractsignature contracts_contractsignature_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractsignature
    ADD CONSTRAINT contracts_contractsignature_pkey PRIMARY KEY (id);


--
-- Name: contracts_contracttarget contracts_contracttarget_contract_id_key; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contracttarget
    ADD CONSTRAINT contracts_contracttarget_contract_id_key UNIQUE (contract_id);


--
-- Name: contracts_contracttarget contracts_contracttarget_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contracttarget
    ADD CONSTRAINT contracts_contracttarget_pkey PRIMARY KEY (id);


--
-- Name: contracts_contracttemplate contracts_contracttemplate_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contracttemplate
    ADD CONSTRAINT contracts_contracttemplate_pkey PRIMARY KEY (id);


--
-- Name: contracts_contracttypedefinition contracts_contracttypedefinition_code_key; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contracttypedefinition
    ADD CONSTRAINT contracts_contracttypedefinition_code_key UNIQUE (code);


--
-- Name: contracts_contracttypedefinition contracts_contracttypedefinition_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contracttypedefinition
    ADD CONSTRAINT contracts_contracttypedefinition_pkey PRIMARY KEY (id);


--
-- Name: contracts_finalapproveddocument contracts_finalapproveddocument_contract_id_key; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_finalapproveddocument
    ADD CONSTRAINT contracts_finalapproveddocument_contract_id_key UNIQUE (contract_id);


--
-- Name: contracts_finalapproveddocument contracts_finalapproveddocument_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_finalapproveddocument
    ADD CONSTRAINT contracts_finalapproveddocument_pkey PRIMARY KEY (id);


--
-- Name: contracts_reminderconfiguration contracts_reminderconfiguration_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_reminderconfiguration
    ADD CONSTRAINT contracts_reminderconfiguration_pkey PRIMARY KEY (id);


--
-- Name: contracts_reminderlog contracts_reminderlog_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_reminderlog
    ADD CONSTRAINT contracts_reminderlog_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: contracts_a_action_5ad5c5_idx; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_a_action_5ad5c5_idx ON public.contracts_auditlog USING btree (action, "timestamp" DESC);


--
-- Name: contracts_a_contrac_be1cfa_idx; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_a_contrac_be1cfa_idx ON public.contracts_auditlog USING btree (contract_id, "timestamp" DESC);


--
-- Name: contracts_auditlog_contract_id_1f60541a; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_auditlog_contract_id_1f60541a ON public.contracts_auditlog USING btree (contract_id);


--
-- Name: contracts_auditlog_user_id_cc49beee; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_auditlog_user_id_cc49beee ON public.contracts_auditlog USING btree (user_id);


--
-- Name: contracts_c_contrac_24bc4b_idx; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_c_contrac_24bc4b_idx ON public.contracts_contractquarter USING btree (contract_id, quarter_number);


--
-- Name: contracts_c_contrac_fd43fa_idx; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_c_contrac_fd43fa_idx ON public.contracts_contract USING btree (contract_type, status);


--
-- Name: contracts_c_role_61c809_idx; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_c_role_61c809_idx ON public.contracts_contractrolepermission USING btree (role, permission);


--
-- Name: contracts_c_status_537325_idx; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_c_status_537325_idx ON public.contracts_contract USING btree (status, end_date);


--
-- Name: contracts_comment_contract_id_55bd579d; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_comment_contract_id_55bd579d ON public.contracts_comment USING btree (contract_id);


--
-- Name: contracts_comment_user_id_16bd0880; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_comment_user_id_16bd0880 ON public.contracts_comment USING btree (user_id);


--
-- Name: contracts_contract_created_by_id_1552fda4; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contract_created_by_id_1552fda4 ON public.contracts_contract USING btree (created_by_id);


--
-- Name: contracts_contract_owner_id_b6fd2bd8; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contract_owner_id_b6fd2bd8 ON public.contracts_contract USING btree (owner_id);


--
-- Name: contracts_contract_parent_contract_id_1643da76; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contract_parent_contract_id_1643da76 ON public.contracts_contract USING btree (parent_contract_id);


--
-- Name: contracts_contractdata_contract_id_4ae811dd; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contractdata_contract_id_4ae811dd ON public.contracts_contractdata USING btree (contract_id);


--
-- Name: contracts_contractdata_submitted_by_id_54e56893; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contractdata_submitted_by_id_54e56893 ON public.contracts_contractdata USING btree (submitted_by_id);


--
-- Name: contracts_contractdatafile_contract_data_id_bea77cca; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contractdatafile_contract_data_id_bea77cca ON public.contracts_contractdatafile USING btree (contract_data_id);


--
-- Name: contracts_contractdocument_contract_id_241d96f0; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contractdocument_contract_id_241d96f0 ON public.contracts_contractdocument USING btree (contract_id);


--
-- Name: contracts_contractdocument_uploaded_by_id_e3197bc9; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contractdocument_uploaded_by_id_e3197bc9 ON public.contracts_contractdocument USING btree (uploaded_by_id);


--
-- Name: contracts_contractdraft_contract_id_498c627a; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contractdraft_contract_id_498c627a ON public.contracts_contractdraft USING btree (contract_id);


--
-- Name: contracts_contractdraft_template_id_0da59165; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contractdraft_template_id_0da59165 ON public.contracts_contractdraft USING btree (template_id);


--
-- Name: contracts_contractfield_contract_type_id_ff6b84d6; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contractfield_contract_type_id_ff6b84d6 ON public.contracts_contractfield USING btree (contract_type_id);


--
-- Name: contracts_contractparticipant_contract_id_d86576c6; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contractparticipant_contract_id_d86576c6 ON public.contracts_contractparticipant USING btree (contract_id);


--
-- Name: contracts_contractparticipant_user_id_462ed066; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contractparticipant_user_id_462ed066 ON public.contracts_contractparticipant USING btree (user_id);


--
-- Name: contracts_contractquarter_contract_id_0bc9d1e9; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contractquarter_contract_id_0bc9d1e9 ON public.contracts_contractquarter USING btree (contract_id);


--
-- Name: contracts_contractsignature_contract_id_79d517d8; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contractsignature_contract_id_79d517d8 ON public.contracts_contractsignature USING btree (contract_id);


--
-- Name: contracts_contractsignature_user_id_21bef7d2; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contractsignature_user_id_21bef7d2 ON public.contracts_contractsignature USING btree (user_id);


--
-- Name: contracts_contracttemplate_contract_type_id_9531e884; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contracttemplate_contract_type_id_9531e884 ON public.contracts_contracttemplate USING btree (contract_type_id);


--
-- Name: contracts_contracttypedefinition_code_a39a18e0_like; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_contracttypedefinition_code_a39a18e0_like ON public.contracts_contracttypedefinition USING btree (code varchar_pattern_ops);


--
-- Name: contracts_finalapproveddocument_uploaded_by_id_4be868e4; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_finalapproveddocument_uploaded_by_id_4be868e4 ON public.contracts_finalapproveddocument USING btree (uploaded_by_id);


--
-- Name: contracts_r_contrac_783826_idx; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_r_contrac_783826_idx ON public.contracts_reminderconfiguration USING btree (contract_type_id, enabled);


--
-- Name: contracts_r_contrac_925f3e_idx; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_r_contrac_925f3e_idx ON public.contracts_reminderconfiguration USING btree (contract_id, enabled);


--
-- Name: contracts_r_contrac_c4c5b1_idx; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_r_contrac_c4c5b1_idx ON public.contracts_reminderlog USING btree (contract_id, scheduled_date DESC);


--
-- Name: contracts_r_reminde_46285b_idx; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_r_reminde_46285b_idx ON public.contracts_reminderconfiguration USING btree (reminder_type, scope, enabled);


--
-- Name: contracts_r_reminde_cd0a46_idx; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_r_reminde_cd0a46_idx ON public.contracts_reminderlog USING btree (reminder_type, status);


--
-- Name: contracts_r_sent_da_e5f644_idx; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_r_sent_da_e5f644_idx ON public.contracts_reminderlog USING btree (sent_date);


--
-- Name: contracts_reminderconfiguration_contract_id_bfc013b1; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_reminderconfiguration_contract_id_bfc013b1 ON public.contracts_reminderconfiguration USING btree (contract_id);


--
-- Name: contracts_reminderconfiguration_contract_type_id_b5c546bb; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_reminderconfiguration_contract_type_id_b5c546bb ON public.contracts_reminderconfiguration USING btree (contract_type_id);


--
-- Name: contracts_reminderlog_contract_id_ec0aebbe; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_reminderlog_contract_id_ec0aebbe ON public.contracts_reminderlog USING btree (contract_id);


--
-- Name: contracts_reminderlog_reminder_config_id_80f5ad11; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX contracts_reminderlog_reminder_config_id_80f5ad11 ON public.contracts_reminderlog USING btree (reminder_config_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- Name: django_celery_beat_periodictask_name_265a36b7_like; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);


--
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: unique_global_reminder; Type: INDEX; Schema: public; Owner: clm_user
--

CREATE UNIQUE INDEX unique_global_reminder ON public.contracts_reminderconfiguration USING btree (reminder_type, scope) WHERE ((contract_id IS NULL) AND (contract_type_id IS NULL));


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_auditlog contracts_auditlog_contract_id_1f60541a_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_auditlog
    ADD CONSTRAINT contracts_auditlog_contract_id_1f60541a_fk_contracts FOREIGN KEY (contract_id) REFERENCES public.contracts_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_auditlog contracts_auditlog_user_id_cc49beee_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_auditlog
    ADD CONSTRAINT contracts_auditlog_user_id_cc49beee_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_comment contracts_comment_contract_id_55bd579d_fk_contracts_contract_id; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_comment
    ADD CONSTRAINT contracts_comment_contract_id_55bd579d_fk_contracts_contract_id FOREIGN KEY (contract_id) REFERENCES public.contracts_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_comment contracts_comment_user_id_16bd0880_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_comment
    ADD CONSTRAINT contracts_comment_user_id_16bd0880_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contract contracts_contract_created_by_id_1552fda4_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contract
    ADD CONSTRAINT contracts_contract_created_by_id_1552fda4_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contract contracts_contract_owner_id_b6fd2bd8_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contract
    ADD CONSTRAINT contracts_contract_owner_id_b6fd2bd8_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contract contracts_contract_parent_contract_id_1643da76_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contract
    ADD CONSTRAINT contracts_contract_parent_contract_id_1643da76_fk_contracts FOREIGN KEY (parent_contract_id) REFERENCES public.contracts_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contractdatafile contracts_contractda_contract_data_id_bea77cca_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractdatafile
    ADD CONSTRAINT contracts_contractda_contract_data_id_bea77cca_fk_contracts FOREIGN KEY (contract_data_id) REFERENCES public.contracts_contractdata(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contractdata contracts_contractda_contract_id_4ae811dd_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractdata
    ADD CONSTRAINT contracts_contractda_contract_id_4ae811dd_fk_contracts FOREIGN KEY (contract_id) REFERENCES public.contracts_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contractdata contracts_contractdata_submitted_by_id_54e56893_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractdata
    ADD CONSTRAINT contracts_contractdata_submitted_by_id_54e56893_fk_auth_user_id FOREIGN KEY (submitted_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contractdocument contracts_contractdo_contract_id_241d96f0_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractdocument
    ADD CONSTRAINT contracts_contractdo_contract_id_241d96f0_fk_contracts FOREIGN KEY (contract_id) REFERENCES public.contracts_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contractdocument contracts_contractdo_uploaded_by_id_e3197bc9_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractdocument
    ADD CONSTRAINT contracts_contractdo_uploaded_by_id_e3197bc9_fk_auth_user FOREIGN KEY (uploaded_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contractdraft contracts_contractdr_contract_id_498c627a_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractdraft
    ADD CONSTRAINT contracts_contractdr_contract_id_498c627a_fk_contracts FOREIGN KEY (contract_id) REFERENCES public.contracts_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contractdraft contracts_contractdr_template_id_0da59165_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractdraft
    ADD CONSTRAINT contracts_contractdr_template_id_0da59165_fk_contracts FOREIGN KEY (template_id) REFERENCES public.contracts_contracttemplate(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contractfield contracts_contractfi_contract_type_id_ff6b84d6_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractfield
    ADD CONSTRAINT contracts_contractfi_contract_type_id_ff6b84d6_fk_contracts FOREIGN KEY (contract_type_id) REFERENCES public.contracts_contracttypedefinition(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contractparticipant contracts_contractpa_contract_id_d86576c6_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractparticipant
    ADD CONSTRAINT contracts_contractpa_contract_id_d86576c6_fk_contracts FOREIGN KEY (contract_id) REFERENCES public.contracts_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contractparticipant contracts_contractparticipant_user_id_462ed066_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractparticipant
    ADD CONSTRAINT contracts_contractparticipant_user_id_462ed066_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contractquarter contracts_contractqu_contract_id_0bc9d1e9_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractquarter
    ADD CONSTRAINT contracts_contractqu_contract_id_0bc9d1e9_fk_contracts FOREIGN KEY (contract_id) REFERENCES public.contracts_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contractsignature contracts_contractsi_contract_id_79d517d8_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractsignature
    ADD CONSTRAINT contracts_contractsi_contract_id_79d517d8_fk_contracts FOREIGN KEY (contract_id) REFERENCES public.contracts_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contractsignature contracts_contractsignature_user_id_21bef7d2_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contractsignature
    ADD CONSTRAINT contracts_contractsignature_user_id_21bef7d2_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contracttarget contracts_contractta_contract_id_3526a32d_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contracttarget
    ADD CONSTRAINT contracts_contractta_contract_id_3526a32d_fk_contracts FOREIGN KEY (contract_id) REFERENCES public.contracts_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_contracttemplate contracts_contractte_contract_type_id_9531e884_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_contracttemplate
    ADD CONSTRAINT contracts_contractte_contract_type_id_9531e884_fk_contracts FOREIGN KEY (contract_type_id) REFERENCES public.contracts_contracttypedefinition(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_finalapproveddocument contracts_finalappro_contract_id_c19168a3_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_finalapproveddocument
    ADD CONSTRAINT contracts_finalappro_contract_id_c19168a3_fk_contracts FOREIGN KEY (contract_id) REFERENCES public.contracts_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_finalapproveddocument contracts_finalappro_uploaded_by_id_4be868e4_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_finalapproveddocument
    ADD CONSTRAINT contracts_finalappro_uploaded_by_id_4be868e4_fk_auth_user FOREIGN KEY (uploaded_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_reminderconfiguration contracts_reminderco_contract_id_bfc013b1_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_reminderconfiguration
    ADD CONSTRAINT contracts_reminderco_contract_id_bfc013b1_fk_contracts FOREIGN KEY (contract_id) REFERENCES public.contracts_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_reminderconfiguration contracts_reminderco_contract_type_id_b5c546bb_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_reminderconfiguration
    ADD CONSTRAINT contracts_reminderco_contract_type_id_b5c546bb_fk_contracts FOREIGN KEY (contract_type_id) REFERENCES public.contracts_contracttypedefinition(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_reminderlog contracts_reminderlo_contract_id_ec0aebbe_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_reminderlog
    ADD CONSTRAINT contracts_reminderlo_contract_id_ec0aebbe_fk_contracts FOREIGN KEY (contract_id) REFERENCES public.contracts_contract(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contracts_reminderlog contracts_reminderlo_reminder_config_id_80f5ad11_fk_contracts; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.contracts_reminderlog
    ADD CONSTRAINT contracts_reminderlo_reminder_config_id_80f5ad11_fk_contracts FOREIGN KEY (reminder_config_id) REFERENCES public.contracts_reminderconfiguration(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: clm_user
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 4CEyuVHZsjchV1dvczrvUZMqMDYpit7TAwKPtW3MJg6Ix3DF4HmG0xx6dj1uPMU

