# Generated by Django 4.2.11 on 2026-03-05 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0025_contract_duration_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason why the document needs revision', verbose_name='Revision Reason')),
                ('status', models.CharField(choices=[('pending', 'Pending Revision'), ('revised', 'Revised - Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revised_at', models.DateTimeField(blank=True, help_text='When the document was re-uploaded', null=True)),
                ('revised_document', models.FileField(blank=True, help_text='The revised/replaced document', null=True, upload_to='business_entity_documents/%Y/%m/')),
                ('approval_notes', models.TextField(blank=True, help_text='Notes from legal reviewer on approval/rejection')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_approvals', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='contracts.businessentitydocument')),
                ('requested_by', models.ForeignKey(help_text='Legal reviewer who requested the revision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_revision_requests', to=settings.AUTH_USER_MODEL)),
                ('revised_by', models.ForeignKey(blank=True, help_text='User who uploaded the revised document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
