# Generated by Django 4.2.11 on 2026-03-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_documentrevisionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('GENERAL_TRADE', 'General Trade Agreement'), ('GENERAL_TRADE_REGULAR', 'General Trade Agreement - Regular'), ('GENERAL_TRADE_PREMIUM', 'General Trade Agreement - Premium'), ('MODERN_TRADE', 'Modern Trade Agreement'), ('DISTRIBUTOR', 'Distributor Agreement'), ('NDA', 'Non-Disclosure Agreement'), ('VENDOR', 'Vendor Agreement'), ('SERVICE', 'Service Agreement'), ('EMPLOYMENT', 'Employment Contract'), ('LEASE', 'Lease Agreement'), ('PURCHASE', 'Purchase Agreement'), ('OTHER', 'Other')], default='OTHER', max_length=25),
        ),
        migrations.AlterField(
            model_name='contracttypedefinition',
            name='code',
            field=models.CharField(choices=[('GENERAL_TRADE', 'General Trade Agreement'), ('GENERAL_TRADE_REGULAR', 'General Trade Agreement - Regular'), ('GENERAL_TRADE_PREMIUM', 'General Trade Agreement - Premium'), ('MODERN_TRADE', 'Modern Trade Agreement'), ('DISTRIBUTOR', 'Distributor Agreement'), ('NDA', 'Non-Disclosure Agreement'), ('VENDOR', 'Vendor Agreement'), ('SERVICE', 'Service Agreement'), ('EMPLOYMENT', 'Employment Contract'), ('LEASE', 'Lease Agreement'), ('PURCHASE', 'Purchase Agreement'), ('OTHER', 'Other')], help_text='Internal contract type code (matches Contract.contract_type)', max_length=25, unique=True),
        ),
    ]
