# Generated by Django 4.2.11 on 2026-01-27 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contract_type', models.CharField(choices=[('NDA', 'Non-Disclosure Agreement'), ('VENDOR', 'Vendor Agreement'), ('SERVICE', 'Service Agreement'), ('EMPLOYMENT', 'Employment Contract'), ('LEASE', 'Lease Agreement'), ('PURCHASE', 'Purchase Agreement'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('party_a', models.CharField(help_text='First party (usually our company)', max_length=255)),
                ('party_b', models.CharField(help_text='Second party (customer/vendor)', max_length=255)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, help_text='Contract value in USD', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('renewal_reminder_days', models.IntegerField(default=30, help_text='Days before expiry to send reminder')),
                ('auto_renew', models.BooleanField(default=False, help_text='Automatically create renewal contract')),
                ('renewal_period_months', models.IntegerField(default=12, help_text='Renewal period in months')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('LEGAL_REVIEW', 'Legal Review'), ('APPROVED', 'Approved'), ('PENDING_SIGNATURE', 'Pending Signature'), ('SIGNED', 'Signed'), ('ACTIVE', 'Active'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('RENEWED', 'Renewed'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contracts', to=settings.AUTH_USER_MODEL)),
                ('parent_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='contracts.contract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_data', models.TextField(help_text='Base64 encoded signature image')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='contract_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='contracts.contract')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_internal', models.BooleanField(default=True, help_text='Internal comments not visible to customers')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contracts.contract')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Contract Created'), ('UPDATE', 'Contract Updated'), ('STATUS_CHANGE', 'Status Changed'), ('DOCUMENT_UPLOAD', 'Document Uploaded'), ('PARTICIPANT_ADDED', 'Participant Added'), ('PARTICIPANT_REMOVED', 'Participant Removed'), ('SIGNATURE_ADDED', 'Signature Added'), ('EMAIL_SENT', 'Email Sent'), ('RENEWAL_REMINDER', 'Renewal Reminder Sent'), ('EXPIRY_CHECK', 'Expiry Check Performed'), ('AUTO_RENEWAL', 'Auto Renewal Created'), ('COMMENT_ADDED', 'Comment Added'), ('APPROVAL_REQUESTED', 'Approval Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='contracts.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContractParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Contract Owner'), ('SALES', 'Sales Representative'), ('LEGAL', 'Legal Reviewer'), ('CUSTOMER', 'Customer'), ('SIGNATORY', 'Signatory'), ('APPROVER', 'Approver')], max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contracts.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'added_at'],
                'unique_together': {('contract', 'user', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'end_date'], name='contracts_c_status_537325_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_type', 'status'], name='contracts_c_contrac_fd43fa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['contract', '-timestamp'], name='contracts_a_contrac_be1cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='contracts_a_action_5ad5c5_idx'),
        ),
    ]
