# Generated by Django 4.2.11 on 2026-01-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_dynamic_contract_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contractdraft',
            name='contracts_draft_unique_version',
        ),
        migrations.RemoveConstraint(
            model_name='contractfield',
            name='contracts_contractfield_unique_field',
        ),
        migrations.AlterUniqueTogether(
            name='contractdraft',
            unique_together={('contract', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='contractfield',
            unique_together={('contract_type', 'field_key')},
        ),
    ]
