# Generated by Django 4.2.11 on 2026-01-27 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_remove_contractdraft_contracts_draft_unique_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractdata',
            options={'ordering': ['-version']},
        ),
        migrations.AddField(
            model_name='contractdata',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractdata',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_data_versions', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contractfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('file', 'File Upload')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='contractdata',
            unique_together={('contract', 'version')},
        ),
        migrations.CreateModel(
            name='ContractDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='contract_data_files/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contracts.contractdata')),
            ],
        ),
    ]
