# Generated by Django 4.2.11 on 2026-01-27 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0004_alter_contractdata_options_contractdata_submitted_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contractparticipant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contractparticipant',
            name='external_email',
            field=models.EmailField(blank=True, help_text='Email for external participants (vendors, customers, signatories)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contractparticipant',
            name='external_name',
            field=models.CharField(blank=True, help_text='Name of external participant', max_length=255),
        ),
        migrations.AddField(
            model_name='contractparticipant',
            name='notification_preference',
            field=models.CharField(choices=[('all', 'All Notifications'), ('critical', 'Critical Actions Only'), ('none', 'No Email Notifications')], default='critical', help_text='Email notification preference for this participant', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractparticipant',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Internal system user (optional if external_email provided)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
