# Generated by Django 4.2.11 on 2026-01-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contractdocument_versioning'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reminderconfiguration',
            name='unique_global_reminder',
        ),
        migrations.RenameIndex(
            model_name='contractquarter',
            new_name='contracts_c_contrac_24bc4b_idx',
            old_name='contract_quarter_idx',
        ),
        migrations.RenameIndex(
            model_name='reminderconfiguration',
            new_name='contracts_r_reminde_46285b_idx',
            old_name='reminder_type_scope_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='reminderconfiguration',
            new_name='contracts_r_contrac_783826_idx',
            old_name='reminder_contract_type_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='reminderconfiguration',
            new_name='contracts_r_contrac_925f3e_idx',
            old_name='reminder_contract_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='reminderlog',
            new_name='contracts_r_contrac_c4c5b1_idx',
            old_name='log_contract_scheduled_idx',
        ),
        migrations.RenameIndex(
            model_name='reminderlog',
            new_name='contracts_r_reminde_cd0a46_idx',
            old_name='log_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reminderlog',
            new_name='contracts_r_sent_da_e5f644_idx',
            old_name='log_sent_date_idx',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('GENERAL_TRADE', 'General Trade Agreement'), ('MODERN_TRADE', 'Modern Trade Agreement'), ('DISTRIBUTOR', 'Distributor Agreement'), ('NDA', 'Non-Disclosure Agreement'), ('VENDOR', 'Vendor Agreement'), ('SERVICE', 'Service Agreement'), ('EMPLOYMENT', 'Employment Contract'), ('LEASE', 'Lease Agreement'), ('PURCHASE', 'Purchase Agreement'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='contracttypedefinition',
            name='code',
            field=models.CharField(choices=[('GENERAL_TRADE', 'General Trade Agreement'), ('MODERN_TRADE', 'Modern Trade Agreement'), ('DISTRIBUTOR', 'Distributor Agreement'), ('NDA', 'Non-Disclosure Agreement'), ('VENDOR', 'Vendor Agreement'), ('SERVICE', 'Service Agreement'), ('EMPLOYMENT', 'Employment Contract'), ('LEASE', 'Lease Agreement'), ('PURCHASE', 'Purchase Agreement'), ('OTHER', 'Other')], help_text='Internal contract type code (matches Contract.contract_type)', max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='reminderconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('contract__isnull', True), ('contract_type__isnull', True)), fields=('reminder_type', 'scope'), name='unique_global_reminder'),
        ),
    ]
