# Generated by Django 4.2.11 on 2026-02-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_remove_reminderconfiguration_unique_global_reminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Contract value in IDR (Indonesian Rupiah)', max_digits=15, null=True),
        ),
    ]
