# Generated by Django 4.2.11 on 2026-02-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_change_contract_value_to_idr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Contract value in IDR (Indonesian Rupiah) - up to 999 trillion', max_digits=18, null=True),
        ),
    ]
