# Generated by Django 4.2.11 on 2026-02-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_contractrolepermission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contractrolepermission',
            new_name='contracts_c_role_61c809_idx',
            old_name='contracts_c_role_pe_6f5f66_idx',
        ),
    ]
