# Generated by Django 4.2.11 on 2026-02-06 06:36

from django.db import migrations
from django.contrib.auth.models import Group


def create_legal_team_group(apps, schema_editor):
    """Create the Legal Team group for auto-assigning legal members to contracts"""
    Group.objects.get_or_create(name='Legal Team')


def delete_legal_team_group(apps, schema_editor):
    """Delete the Legal Team group on rollback"""
    Group.objects.filter(name='Legal Team').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_rename_contracts_c_role_pe_6f5f66_idx_contracts_c_role_61c809_idx'),
    ]

    operations = [
        migrations.RunPython(create_legal_team_group, delete_legal_team_group),
    ]
