# Generated by Django 4.2.11 on 2026-02-06 06:39

from django.db import migrations


def migrate_statuses(apps, schema_editor):
    """Migrate old statuses to new simplified workflow"""
    Contract = apps.get_model('contracts', 'Contract')
    
    # Status mapping: old → new
    status_map = {
        'DRAFT': 'DRAFT',
        'DATA_COMPLETED': 'DRAFT',
        'PENDING_REVIEW': 'SUBMITTED',
        'LEGAL_REVIEW': 'LEGAL_REVIEW',
        'APPROVED': 'APPROVED',
        'PENDING_SIGNATURE': 'APPROVED',
        'SIGNED': 'ACTIVE',
        'ACTIVE': 'ACTIVE',
        'EXPIRING_SOON': 'ACTIVE',
        'EXPIRED': 'TERMINATED',
        'RENEWED': 'ACTIVE',
        'TERMINATED': 'TERMINATED',
    }
    
    for contract in Contract.objects.all():
        if contract.status in status_map:
            contract.status = status_map[contract.status]
            contract.save(update_fields=['status'])


def reverse_migrate_statuses(apps, schema_editor):
    """No way to reverse this safely, keeping as is"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_create_legal_team_group'),
    ]

    operations = [
        migrations.RunPython(migrate_statuses, reverse_migrate_statuses),
    ]
