# Generated by Django 4.2.11 on 2026-02-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_simplify_contract_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('LEGAL_REVIEW', 'Legal Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=20),
        ),
    ]
