# Generated by Django 4.2.11 on 2026-02-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('LEGAL_REVIEW', 'Legal Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('EXPIRING_SOON', 'Expiring Soon'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=20),
        ),
    ]
