# Generated by Django 4.2.11 on 2026-02-06 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0019_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Contract Created'), ('UPDATE', 'Contract Updated'), ('STATUS_CHANGE', 'Status Changed'), ('DOCUMENT_UPLOAD', 'Document Uploaded'), ('FINAL_DOCUMENT_UPLOAD', 'Final Document Uploaded'), ('PARTICIPANT_ADDED', 'Participant Added'), ('PARTICIPANT_REMOVED', 'Participant Removed'), ('SIGNATURE_ADDED', 'Signature Added'), ('EMAIL_SENT', 'Email Sent'), ('RENEWAL_REMINDER', 'Renewal Reminder Sent'), ('EXPIRY_CHECK', 'Expiry Check Performed'), ('AUTO_RENEWAL', 'Auto Renewal Created'), ('COMMENT_ADDED', 'Comment Added'), ('APPROVAL_REQUESTED', 'Approval Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DATA_SUBMITTED', 'Structured Data Submitted'), ('DRAFT_GENERATED', 'Draft Generated'), ('DRAFT_UPDATED', 'Draft Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contractrolepermission',
            name='permission',
            field=models.CharField(choices=[('view_contract', 'View contract'), ('edit_contract', 'Edit contract'), ('delete_contract', 'Delete contract'), ('update_status', 'Update status'), ('manage_participants', 'Manage participants'), ('add_document', 'Add documents'), ('upload_final_document', 'Upload final approved document'), ('add_comment', 'Add comments'), ('edit_structured_data', 'Edit structured data'), ('regenerate_draft', 'Regenerate drafts')], max_length=32),
        ),
        migrations.CreateModel(
            name='FinalApprovedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='final_contracts/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about the final signed document')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_approved_document', to='contracts.contract')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_final_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
