# Generated by Django 4.2.11 on 2026-03-03 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0021_business_entity_wizard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessentitydocument',
            name='contract',
            field=models.ForeignKey(help_text='Contract this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='business_entity_documents', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='businessentitydocument',
            name='document',
            field=models.FileField(help_text='Upload the required document', upload_to='business_entity_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='businessentitydocument',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or description'),
        ),
        migrations.AlterField(
            model_name='businessentitydocument',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='businessentitydocument',
            unique_together={('contract', 'document_type')},
        ),
    ]
