# Generated by Django 4.2.11 on 2026-03-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0022_alter_businessentitydocument_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full legal name of your company (e.g., PT. ABC Indonesia)', max_length=255, unique=True, verbose_name='Company Legal Name')),
                ('business_entity_type', models.CharField(choices=[('PT', 'Perusahaan Terbatas (PT)'), ('CV', 'Commanditaire Vennootschap (CV)'), ('PERORANGAN', 'Perorangan')], help_text='PT, CV, or Perorangan', max_length=20, verbose_name='Business Entity Type')),
                ('address', models.TextField(help_text='Full address of the company', verbose_name='Business Address')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('npwp', models.CharField(blank=True, help_text='Tax identification number', max_length=50, verbose_name='NPWP')),
                ('nib', models.CharField(blank=True, help_text='Business registration number', max_length=50, verbose_name='NIB')),
                ('registration_document', models.FileField(blank=True, help_text='Company registration document (e.g., Akta Pendirian)', null=True, upload_to='company/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
