# Generated by Django 4.2.11 on 2026-03-04 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0023_companyprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'ordering': ['-is_active', '-updated_at'], 'verbose_name': 'Company Profile', 'verbose_name_plural': 'Company Profiles'},
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='registration_document',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='akta_pendirian_number',
            field=models.CharField(blank=True, help_text='Certificate of Incorporation number', max_length=100, verbose_name='Akta Pendirian Number'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one profile can be active at a time', verbose_name='Active Profile'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='legal_representative_name',
            field=models.CharField(blank=True, help_text='Name of person authorized to sign contracts', max_length=255, verbose_name='Legal Representative'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='legal_representative_title',
            field=models.CharField(blank=True, help_text='e.g., Direktur Utama, CEO', max_length=100, verbose_name='Representative Title'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='short_name',
            field=models.CharField(blank=True, help_text='Abbreviated name for display', max_length=100, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profile_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='business_entity_type',
            field=models.CharField(choices=[('PT', 'Perusahaan Terbatas (PT)'), ('CV', 'Commanditaire Vennootschap (CV)'), ('PERORANGAN', 'Perorangan')], max_length=20, verbose_name='Entity Type'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Company Email'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(help_text='Full legal name (e.g., PT. PERFECT COMPANION INDONESIA)', max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='nib',
            field=models.CharField(blank=True, help_text='Nomor Induk Berusaha', max_length=50, verbose_name='NIB'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='npwp',
            field=models.CharField(blank=True, help_text='Nomor Pokok Wajib Pajak', max_length=50, verbose_name='NPWP'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone Number'),
        ),
    ]
