# Generated by Django 4.2.11 on 2026-03-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_alter_companyprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='Contract duration in days (alternative to end date)', null=True, verbose_name='Duration (days)'),
        ),
    ]
