# Generated by Django 4.2.11 on 2026-03-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0030_alter_contract_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, help_text='Generated at legal approval (e.g., 01.001/PCI/Sales/2026)', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='issuing_company_code',
            field=models.CharField(blank=True, help_text='Issuing company code used in contract number (e.g., PCI)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='issuing_company_name',
            field=models.CharField(blank=True, help_text='Issuing company name (required for Vendor contracts)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('LEGAL_REVIEW', 'Legal Review'), ('APPROVED', 'Approved'), ('SIGNED', 'Signed'), ('ACTIVE', 'Active'), ('EXPIRING_SOON', 'Expiring Soon'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type_code', models.CharField(help_text='01, 02, 03, 04', max_length=2)),
                ('year', models.PositiveIntegerField()),
                ('company_key', models.CharField(blank=True, help_text='Company key for Vendor (04). Null for non-vendor types.', max_length=100, null=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['contract_type_code', '-year', 'company_key'],
                'unique_together': {('contract_type_code', 'year', 'company_key')},
            },
        ),
    ]
