# Generated by Django 4.2.11 on 2026-04-01 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0020_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='business_entity_type',
            field=models.CharField(blank=True, choices=[('PT', 'Perusahaan Terbatas (PT)'), ('CV', 'Commanditaire Vennootschap (CV)'), ('PERORANGAN', 'Perorangan')], max_length=20, null=True, verbose_name='Business Entity Type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='Contract duration in days (alternative to end date)', null=True, verbose_name='Duration (days)'),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full legal name (e.g., PT. PERFECT COMPANION INDONESIA)', max_length=255, verbose_name='Company Name')),
                ('short_name', models.CharField(blank=True, help_text='Abbreviated name for display', max_length=100, verbose_name='Short Name')),
                ('business_entity_type', models.CharField(choices=[('PT', 'Perusahaan Terbatas (PT)'), ('CV', 'Commanditaire Vennootschap (CV)'), ('PERORANGAN', 'Perorangan')], max_length=20, verbose_name='Entity Type')),
                ('npwp', models.CharField(blank=True, help_text='Nomor Pokok Wajib Pajak', max_length=50, verbose_name='NPWP')),
                ('nib', models.CharField(blank=True, help_text='Nomor Induk Berusaha', max_length=50, verbose_name='NIB')),
                ('akta_pendirian_number', models.CharField(blank=True, help_text='Certificate of Incorporation number', max_length=100, verbose_name='Akta Pendirian Number')),
                ('address', models.TextField(blank=True, verbose_name='Company Address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Company Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('legal_representative_name', models.CharField(blank=True, help_text='Name of person authorized to sign contracts', max_length=255, verbose_name='Legal Representative')),
                ('legal_representative_title', models.CharField(blank=True, help_text='e.g., Direktur Utama, CEO', max_length=100, verbose_name='Representative Title')),
                ('is_active', models.BooleanField(default=True, help_text='Only one profile can be active at a time', verbose_name='Active Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profile_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessEntityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AKTA_PENDIRIAN', 'Akta Pendirian'), ('NPWP', 'NPWP'), ('NIB', 'NIB (Nomor Induk Berusaha)'), ('KTP_PENANGGUNG_JAWAB', 'KTP Penanggung Jawab'), ('PERIZINAN_LAINNYA', 'Perizinan Lainnya'), ('KTP', 'KTP')], max_length=50, verbose_name='Document Type')),
                ('document', models.FileField(help_text='Upload the required document', upload_to='business_entity_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or description')),
                ('contract', models.ForeignKey(help_text='Contract this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='business_entity_documents', to='contracts.contract')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_type', 'uploaded_at'],
                'unique_together': {('contract', 'document_type')},
            },
        ),
    ]
